ALTER TABLE POST_COMMENT DROP CONSTRAINT FK_POST_COMMENT_AUTHOR_ID
ALTER TABLE POST_COMMENT DROP CONSTRAINT FK_POST_COMMENT_POST_ID
ALTER TABLE POST DROP CONSTRAINT FK_POST_AUTHOR_ID
ALTER TABLE Post_IMAGES DROP CONSTRAINT FK_Post_IMAGES_Post_ID
ALTER TABLE POST_TAG DROP CONSTRAINT FK_POST_TAG_Post_ID
ALTER TABLE POST_TAG DROP CONSTRAINT FK_POST_TAG_tags_ID
DROP TABLE POST_COMMENT CASCADE
DROP TABLE POST CASCADE
DROP TABLE TAG CASCADE
DROP TABLE AUTHOR CASCADE
DROP TABLE Post_IMAGES CASCADE
DROP TABLE POST_TAG CASCADE
DROP SEQUENCE SEQ_GEN_SEQUENCE
